services:
  forgeborn-api:
    image: forgeborn-api:dev
    container_name: forgeborn-api
    build:
      context: ./Forgeborn.Server
      dockerfile: Dockerfile
    env_file:
      - ./Forgeborn.Server/.env
    ports:
      - "8080:8080"

  forgeborn-ui:
    build:
      context: ./forgeborn.client
      dockerfile: Dockerfile
    container_name: forgeborn-ui
    image: forgeborn-ui:dev
    env_file:
      - ./forgeborn.client/.env
    ports:
      - "3000:3000"
    tty: true
    depends_on:
      - forgeborn-api