// <auto-generated />
using System;
using System.Collections.Generic;
using Forgeborn.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Forgeborn.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251106183416_UpdateModelsAndControllers")]
    partial class UpdateModelsAndControllers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Forgeborn.Server.Models.CharacterRulesets", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("RulesetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("RulesetId");

                    b.ToTable("CharacterRulesets");
                });

            modelBuilder.Entity("Forgeborn.Server.Models.Characters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Background")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Charisma")
                        .HasColumnType("int");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Constitution")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Dexterity")
                        .HasColumnType("int");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<string>("Inventory")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("Journal")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Race")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Wisdom")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Forgeborn.Server.Models.Items.AdventuringGears", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Attunement")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Cost")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Rarity")
                        .HasColumnType("int");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("WondrousItem")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("AdventuringGears");
                });

            modelBuilder.Entity("Forgeborn.Server.Models.Items.Ammunitions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Attunement")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Cost")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Rarity")
                        .HasColumnType("int");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("WondrousItem")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Ammunitions");
                });

            modelBuilder.Entity("Forgeborn.Server.Models.Items.Armors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArmorClass")
                        .HasColumnType("int");

                    b.Property<bool>("Attunement")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Cost")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Rarity")
                        .HasColumnType("int");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("WondrousItem")
                        .HasColumnType("tinyint(1)");

                    b.ComplexProperty<Dictionary<string, object>>("Traits", "Forgeborn.Server.Models.Items.Armors.Traits#ArmorTraits", b1 =>
                        {
                            b1.Property<bool>("Heavy")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("Light")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("Medium")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("Shield")
                                .HasColumnType("tinyint(1)");
                        });

                    b.HasKey("Id");

                    b.ToTable("Armors");
                });

            modelBuilder.Entity("Forgeborn.Server.Models.Items.Mounts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Attunement")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Cost")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Rarity")
                        .HasColumnType("int");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("WondrousItem")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Mounts");
                });

            modelBuilder.Entity("Forgeborn.Server.Models.Items.SpellScrolls", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Attunement")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Cost")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Rarity")
                        .HasColumnType("int");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("WondrousItem")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("SpellScrolls");
                });

            modelBuilder.Entity("Forgeborn.Server.Models.Items.Tools", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Attunement")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Cost")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Rarity")
                        .HasColumnType("int");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("WondrousItem")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Tools");
                });

            modelBuilder.Entity("Forgeborn.Server.Models.Items.Vehicles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Attunement")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Cost")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Rarity")
                        .HasColumnType("int");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<int>("VehicleType")
                        .HasColumnType("int");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("WondrousItem")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("Forgeborn.Server.Models.Items.Weapons", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Attack")
                        .HasColumnType("int");

                    b.Property<bool>("Attunement")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Cost")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Damage")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Rarity")
                        .HasColumnType("int");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("WondrousItem")
                        .HasColumnType("tinyint(1)");

                    b.ComplexProperty<Dictionary<string, object>>("DamageType", "Forgeborn.Server.Models.Items.Weapons.DamageType#DmgTypeStruct", b1 =>
                        {
                            b1.Property<bool>("isAcid")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("isBludgeoning")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("isCold")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("isFire")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("isForce")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("isLightning")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("isNecrotic")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("isPiercing")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("isPoison")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("isPsychic")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("isRadiant")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("isSlashing")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("isThunder")
                                .HasColumnType("tinyint(1)");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Traits", "Forgeborn.Server.Models.Items.Weapons.Traits#WeaponTraits", b1 =>
                        {
                            b1.Property<bool>("ammunition")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("canBeThrown")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("finesse")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("heavy")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("light")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("loading")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("martial")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("melee")
                                .HasColumnType("tinyint(1)");

                            b1.Property<int>("range")
                                .HasColumnType("int");

                            b1.Property<bool>("ranged")
                                .HasColumnType("tinyint(1)");

                            b1.Property<int>("reach")
                                .HasColumnType("int");

                            b1.Property<bool>("simple")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("staff")
                                .HasColumnType("tinyint(1)");
                        });

                    b.HasKey("Id");

                    b.ToTable("Weapons");
                });

            modelBuilder.Entity("Forgeborn.Server.Models.Lobbys", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Lobbys");
                });

            modelBuilder.Entity("Forgeborn.Server.Models.Players", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<bool>("IsHost")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("LobbyId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("LobbyId");

                    b.HasIndex("UserId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Forgeborn.Server.Models.Rulesets", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Rulesets");
                });

            modelBuilder.Entity("Forgeborn.Server.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Forgeborn.Server.Models.CharacterRulesets", b =>
                {
                    b.HasOne("Forgeborn.Server.Models.Characters", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Forgeborn.Server.Models.Rulesets", "Ruleset")
                        .WithMany()
                        .HasForeignKey("RulesetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Ruleset");
                });

            modelBuilder.Entity("Forgeborn.Server.Models.Characters", b =>
                {
                    b.HasOne("Forgeborn.Server.Models.Users", "User")
                        .WithMany("Characters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Forgeborn.Server.Models.Players", b =>
                {
                    b.HasOne("Forgeborn.Server.Models.Characters", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Forgeborn.Server.Models.Lobbys", "Lobby")
                        .WithMany("Players")
                        .HasForeignKey("LobbyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Forgeborn.Server.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Lobby");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Forgeborn.Server.Models.Rulesets", b =>
                {
                    b.HasOne("Forgeborn.Server.Models.Characters", "CreatedBy")
                        .WithMany("Players")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Forgeborn.Server.Models.Characters", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("Forgeborn.Server.Models.Lobbys", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("Forgeborn.Server.Models.Users", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
