name: Forgeborn UI Docker Build & Push - Dev

on:
  push:
    branches: [ "dev" ]
    paths:
      - 'forgeborn.client/**'

permissions:
  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: "Login to Docker Registry"
        uses: "docker/login-action@v3"
        with:
          registry: docker-registry.graknet.ca
          username: ${{ vars.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASS }}

      - name: Set up QEMU
        uses: "docker/setup-qemu-action@v3"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: "./forgeborn.client"
          push: true
          tags: docker-registry.graknet.ca/forgeborn-ui:dev

